
theme: jekyll-theme-minimal
title: CV template N.Eric
description: Bookmark this to keep an eye on my project updates!
social-network-links: #find me here
  email: "erickykress1@gmail.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: Kress2000
